### ISSUE TITLE
BadRequestError

### ISSUE THREAD

**Issue by bschultz** [versx/DataParser#33]
Seeing this sometimes:
```
2020-09-09 00:01 +02:00: BadRequestError: request aborted
    at IncomingMessage.onAborted (/volume1/RDM/DataParser/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:310:20)
    at abortIncoming (_http_server.js:532:9)
    at socketOnClose (_http_server.js:525:3)
    at Socket.emit (events.js:322:22)
    at TCP.<anonymous> (net.js:672:12)
```

Don't know exactly when this happens

**Comment by versx** [comment]
Not sure what exactly causes this either, I've seen posts mentioning that it's a NodeJS problem with the uri being too long and incorrectly returning a 400 status (not sure if that's still the case), or a connection is maybe closed prematurely.

Maybe we should increase the max acceptable payload size. https://github.com/versx/DataParser/blob/master/src/index.js#L60

I've seen this error in DCM occasionally too.
